### PR TITLE
Fixed README.md spelling typos

### PR DESCRIPTION
**Pull request by crpietschmann**

### CODE REVIEW

**Comment by crpietschmann** [comment]
@stevenfollis Is anyone maintaining this project anymore?

**Comment by crpietschmann** [comment]
I guess you put in the README.md that this project has been abandoned... Too bad you didn't merge my improvements in when you did that. Alrighty, I guess.....

**Comment by stevenfollis** [comment]
Hi @crpietschmann, sorry about that! I transitioned off the team some time ago and can no longer merge. Copying @mioteg in case he assist.

**Comment by mioteg** [comment]
Hi @crpietschmann, sorry about that. I just merged, and fixed the typo that got lost due to the later change. Thanks for the notification.

**Pull request merged**
